sudo: required

language: php

php:
  - 7.0
  - 7.1
  - 7.2

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_script:
  - travis_retry composer self-update
  - travis_wait 30 composer update ${COMPOSER_FLAGS} -vvv --no-interaction --prefer-dist

script:
  - composer validate --strict
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
